[project]
name = "file-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "pefile>=2024.8.26",
    "pyelftools>=0.32",
    "python-magic>=0.4.27",
    "tqdm>=4.67.1",
]
